name: Test workflow call

on: workflow_call

jobs:
  workflow_call_job:
    runs-on: ubuntu-latest
    name: Workflow Call Job
    if: github.event.pull_request.draft == false
    steps:
      - name: Echo
        run: echo "Hello, workflow!"
