on: pull_request

jobs:
  job-zero:
    name: Job 0
    runs-on: ubuntu-latest
    outputs:
      isTrue: ${{ 'false' }}
    steps:
      - name: Test
        run: echo "Test"

  job-one:
    name: Job 1
    needs: job-zero
    if: ${{ needs.job-zero.outputs.isTrue == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Job 1
        run: echo "Run Job 1"

  job-two:
    needs: job-one
    name: job-two
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Run Job 2
        run: |
          echo 'Result: ${{toJSON(needs.job-one.result)}}'
