on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test: 
    uses: ./.github/workflows/test.yml

  test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello, world!"
